mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.sixsixsix.model
  configuration:
    map-underscore-to-camel-case: true

sun-mirror:
  scan-package: com.yunbix.manager.controller
